### PR TITLE
Final exponention

### PR DESCRIPTION
**Pull request by ArturNowakSch**

### CODE REVIEW

**Comment by ArturNowakSch** [comment]
@NONTII do you think it finally works?

**Comment by NONTII** [comment]
@ArturNowakSch いいえ

**Comment by ArturNowakSch** [comment]
@wojtekwro29 what about you? do you think it works?

**Comment by wojtekwro29** [comment]
everything git gud

**Comment by ArturNowakSch** [comment]
wonderful mi amigo @wojtekwro29 @wojtekwro29 

chipi

**Pull request merged**
